### ISSUE TITLE
[BUG] Version range of DOMPurify is invalid and does not work with latest DOMPurify on SSR

### ISSUE THREAD

**Issue by GerkinDev** [TinkoffCreditSystems/ng-dompurify#65]
# 🐞 Bug report

### Description

`ng-dompurify` is incompatible with `dompurify@2.2.6` and `dompurify@2.2.5` in SSR mode, but `dompurify@2.2.4` works as expected. It seems that the actual underlying method to retrieve the `parentNode` getter is invalid to work with `domino`, the DOM emulation used in SSR setups, and was changed in the diff below.

https://github.com/cure53/DOMPurify/compare/2.2.4..2.2.6

The error is like this:

```
 An error was catched by the global error handler.
 TypeError: getParentNode is not a function
    at _sanitizeElements (.../main.js:2630:26)
    at Function.DOMPurify.sanitize (.../main.js:2943:11)
    at NgDompurifySanitizer.sanitize (.../main.js:67707:30
```

### Reproduction

Install latest `ng-dompurify` and `dompurify@>=2.2.5`, and use it in a SSR setup on platform-server.

### Expected behavior

This should work as expected

### Versions

-   OS: [e.g. iOS]: Node
-   Browser [e.g. chrome, safari]: Node
-   Angular [e.g. 8]: 11.x.x

### Additional context

Using SSR is important to reproduce the error, since it does not define the `parentNode` as a proper property using `Object.defineProperty`, thus causing the invalid behavior in DOMPurify. Maybe this would be relevant to inform the `dompurify` maintainer about this issue, but this dependency version range should nonetheless be excluded from this package. This could also be reverted if a later version of `domino` changes its property definition method.

I managed to fix this issue by specifying the following in my app's `package.json`:

```jsonc
{
  // ...
  "dependencies": {
    // ...
    "dompurify": "^2.0.0 <2.2.5",
    // ...
  }
}
```

**Comment by splincode** [comment]
https://github.com/Tinkoff/ng-dompurify/pull/105
